Odiseo\Bundle\MotorOptimoBundle\Entity\Post:
    type: entity
    table: Post
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 60
        text:
            type: string
            length: 255              
        postType:
            type: integer
            length: 1
        date:
            column: date
            type: datetime
            gedmo:
              timestampable:
                on: create   

    manyToOne:
        tag:
            targetEntity: Tag
            inversedBy: posts
            cascade: ["persist", "merge"]
            joinColumn:
                name: tag_id
                referencedColumnName: id
                onDelete: SET NULL
        resource:
            targetEntity: Resource
            inversedBy: posts
            cascade: ["persist", "merge"]
            joinColumn:
                name: resource_id
                referencedColumnName: id
                onDelete: SET NULL                
    lifecycleCallbacks: {  }