Odiseo\Bundle\MotorOptimoBundle\Entity\Tag:
    type: entity
    table: Tag
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        tag:
            type: string
            length: 255
 
    oneToMany:
        posts:
            targetEntity: Post
            mappedBy: tag
    lifecycleCallbacks: {  }