odiseo_motor_optimo_backend_homepage:
    path:     /
    defaults: { _controller: "OdiseoMotorOptimoBundle:Backend/Main:index" }
    
odiseo_motor_optimo_backend_adminProducts:
    path:     /adminProducts
    defaults: { _controller: "OdiseoMotorOptimoBundle:Backend/Products:adminProducts" }  
    
odiseo_motor_optimo_backend_adminSlider:
    path:     /adminSlider
    defaults: { _controller: "OdiseoMotorOptimoBundle:Backend/Slider:adminSlider" }  

odiseo_motor_optimo_backend_adminTips:
    path:     /adminTips
    defaults: { _controller: "OdiseoMotorOptimoBundle:Backend/Tips:adminTips" } 
    
odiseo_motor_optimo_backend_viewListProducts:
    path:     /adminProducts/listProducts
    defaults: { _controller: "OdiseoMotorOptimoBundle:Backend/Products:viewAllProducts" }  
 
odiseo_motor_optimo_backend_addProducts:
    path:     /adminProducts/addProducts
    defaults: { _controller: "OdiseoMotorOptimoBundle:Backend/Products:addProducts" }   